/* Copyright (c) 2013, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_ILI9881C_720P_VIDEO_H_
#define _PANEL_ILI9881C_720P_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config ili9881c_720p_video_panel_data = {
	"qcom,mdss_dsi_ili9881c_720p_video",    /* panel_node_id */
    "dsi:0:",   /* panel_controller */
    "qcom,mdss-dsi-panel",  /* panel_compatible */
	10, /* panel_interface */ 
    0,  /* panel_type */ 
    "DISPLAY_1", /* panel_destination */
    0,  /* panel_orientation */ 
    0,  /* panel_clockrate */ 
    60, /* panel_framerate */ 
    0,  /* panel_channelid */
    0,  /* dsi_virtualchannel_id */
    0,  /* panel_broadcast_mode */ 
    0,  /* panel_lp11_init */
    0,  /* panel_init_delay */
    0,  /* dsi_stream */
    0,  /*  interleave_mode */
    0,  /* panel_bitclock_freq */
    0,  /* panel_operating_mode */
    0,  /* panel_with_enable_gpio */
    0,  /* mode_gpio_state */
    "qcom,mdss_dsi_lt8912b_ZT101IP35025_dsi1_video"    /* slave_panel_node_id */
};
//	"qcom,mdss_dsi_ili9881c_720p_video" 
/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution ili9881c_720p_video_panel_res = {
  1280, 720, 110, 220, 40, 0, 5, 20, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel color information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info ili9881c_720p_video_color = {
	24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel on/off command information                                          */
/*---------------------------------------------------------------------------*/


/*
static char read_id_00h_cmd[] = {0x00, 0x00, 0x06, 0xa0};	// DTYPE_DCS_READ 

static struct mipi_dsi_cmd ili9881c_720p_video_on_command[] =
    {sizeof(read_id_00h_cmd), read_id_00h_cmd};

#define	ILI9881C_720P_VIDEO_ON_COMMAND 1
*/
 
static char ili9881c_720p_videooff_cmd0[] = {
	0x28, 0x00, 0x05, 0x80
};
 
static char ili9881c_720p_videooff_cmd1[] = {
	0x10, 0x00, 0x05, 0x80
};
 
static struct mipi_dsi_cmd ili9881c_720p_video_off_command[] = {
	{0x4, ili9881c_720p_videooff_cmd0, 0x32},
	{0x4, ili9881c_720p_videooff_cmd1, 0x78}
};
 
#define ILI9881C_720P_VIDEO_OFF_COMMAND 2
 
 
static struct command_state ili9881c_720p_video_state = {
	0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/
static struct commandpanel_info ili9881c_720p_video_command_panel = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/
static struct videopanel_info ili9881c_720p_video_video_panel = {
	0, 0, 0, 0, 1, 1, 1, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane configuration                                                        */
/*---------------------------------------------------------------------------*/
static struct lane_configuration ili9881c_720p_video_lane_config = {
	4, 0, 1, 1, 1, 1, 0
};

/*---------------------------------------------------------------------------*/
/* Panel timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t ili9881c_720p_video_timings[] = {
  0x7F, 0x1c, 0x12, 0x00, 0x40, 0x44, 0x16, 0x1e, 0x17, 0x03, 0x04, 0x00
};
 
static struct panel_timing ili9881c_720p_video_timing_info = {
  0x0, 0x04, 0x04, 0x1B
};
 
/*---------------------------------------------------------------------------*/
/* Panel reset sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence ili9881c_720p_video_reset_seq = {
{ 1, 0, 1, }, { 20, 10, 200, }, 2
};
 
/*---------------------------------------------------------------------------*/
/* Backlight setting                                                         */
/*---------------------------------------------------------------------------*/
static struct backlight ili9881c_720p_video_backlight = {
	1, 1, 4095, 200, 1, "PMIC_8941"
};

#define ILI9881C_720P_VIDEO_SIGNATURE 0x9800

#endif /*_PANEL_ILI9881C_720P_VIDEO_H_*/
