#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FIBOCOM_VIRTUAL_TOUCHSCREEN)  += virtual_touch.o
#obj-$(CONFIG_FIBOCOM_TOUCHSCREEN_FT5X06)		+= ft5x06/
obj-$(CONFIG_FIBOCOM_TOUCHSCREEN_GT9XX)		+= gt9xx/


