#gt915 touchpanel driver
obj-$(CONFIG_FIBOCOM_TOUCHSCREEN_GT9XX)	+= gt9xx.o
#gt915 update file
obj-$(CONFIG_FIBOCOM_GT9XX_TOUCHPANEL_UPDATE)+= gt9xx_update.o
#debug tool
obj-$(CONFIG_FIBOCOM_GT9XX_TOUCHPANEL_TOOL)+= goodix_tool.o